# Generated by Django 5.0 on 2023-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('debito', 'Cartão de Débito'), ('credito_vista', 'Cartão de Crédito à Vista'), ('credito_parcelado', 'Cartão de Crédito Parcelado'), ('dinheiro', 'Dinheiro'), ('fiado', 'Fiado')], max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('nome_procedimento', models.CharField(max_length=100)),
            ],
        ),
    ]
