# Generated by Django 5.0 on 2023-12-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('debito', 'Débito'), ('credito_vista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado'), ('dinheiro', 'Dinheiro'), ('fiado', 'Fiado')], max_length=20),
        ),
    ]
