# Generated by Django 5.0 on 2023-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvendas', '0002_venda_nome_cliente_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('debito', 'Débito'), ('credito_vista', 'Crédito'), ('dinheiro', 'Dinheiro'), ('troca', 'Troca'), ('fiado', 'Fiado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome_procedimento',
            field=models.CharField(choices=[('corte', 'Corte'), ('escova', 'Escova'), ('luzes', 'Luzes'), ('mecha', 'Mecha'), ('tratamento', 'Selagem'), ('ozonio', 'Ozônio'), ('plastica', 'Plástica'), ('coloracao', 'Coloração'), ('outro', 'Outros')], max_length=30),
        ),
    ]
